// ReSharper disable once CheckNamespace
namespace Aspid.FastTools.Ids
{
    /// <summary>
    /// Contract for id structs generated by <c>IdStructGenerator</c> and consumed by
    /// <see cref="IdRegistry{T}"/>.
    /// Each implementing struct is bound to exactly one registry asset.
    /// </summary>
    public interface IId
    {
        /// <summary>
        /// The stable integer value that identifies this id within its registry.
        /// </summary>
        public int Id { get; }
    }
}
